name: Create Release

on:
  push:
    branches:
      - "stable"

env:
  NODE_VERSION: "20.x"

jobs:
  create-release:
    steps:
      - name: Generator token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.GH_RELEASE_APP_ID }}
          private_key: ${{ secrets.GH_RELEASE_APP_PRIVATE_KEY }}
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.generate_token.outputs.token }}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install Dependencies
        run: npm ci
      - name: Semantic Release
        id: semantic-release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
    outputs:
      version: ${{ steps.semantic-release.outputs.nextVersion }}

  rebase-main:
    runs-on: ubuntu-latest
    needs: create-release
    steps:
      - name: Generator token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.GH_RELEASE_APP_ID }}
          private_key: ${{ secrets.GH_RELEASE_APP_PRIVATE_KEY }}
      - name: Checkout all branches
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.generate_token.outputs.token }}
      - name: Checkout main branch
        run: git checkout main
      - name: Rebase main from stable
        run: |
          git fetch origin
          git rebase origin/stable
      - name: Push changes
        run: |
          git push origin main
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
